# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    ignore:
      - dependency-name: "org.mnode.ical4j:ical4j-vcard"
        update-types:
          - "version-update:semver-patch"
          - "version-update:semver-minor"
          - "version-update:semver-major"
      - dependency-name: "info.picocli:picocli"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
      - dependency-name: "org.springframework:spring-framework-bom"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
      - dependency-name: "org.springframework.boot:*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-major"
      - dependency-name: "org.junit.jupiter:*"
        versions:
          - "[6,)"
      - dependency-name: "org.junit.platform:*"
        versions:
          - "[6,)"
      - dependency-name: "org.mockito:*"
        versions:
          - "[5,)"
      - dependency-name: "org.junit-pioneer:junit-pioneer"
        versions:
          - "[2,)"
      - dependency-name: "com.mycila:license-maven-plugin"
        versions:
          - "[5,)"
      - dependency-name: "org.apache.karaf.tooling:karaf-maven-plugin"
        versions:
          - "[4.4.11,)"
