/*
 * Copyright © 2009 Benny Bottema (benny@bennybottema.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.simplejavamail.internal.smimesupport;

import org.junit.jupiter.api.Test;
import org.simplejavamail.api.email.Email;
import org.simplejavamail.api.email.OriginalSmimeDetails.VerificationStatus;
import org.simplejavamail.converter.EmailConverter;

import java.io.ByteArrayInputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Base64;

import static demo.ResourceFolderHelper.determineResourceFolder;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Uses a detached S/MIME message generated by OpenSSL 3.0.13 on Ubuntu 24.04. The fixture is Base64 encoded so Git
 * cannot rewrite the line endings that are covered by the signature.
 */
public class OpenSslSmimeInteroperabilityTest {

	private static final Path OPENSSL_DETACHED_SIGNATURE = Paths.get(
			determineResourceFolder("simple-java-mail"), "test", "resources", "smime",
			"openssl-detached-signed.eml.b64");

	@Test
	public void verifiesDetachedSignatureGeneratedByOpenSsl() throws Exception {
		final byte[] wireMessage = readOpenSslFixture();

		final Email email = EmailConverter.emlToEmail(new ByteArrayInputStream(wireMessage));

		assertThat(email.getPlainText()).contains("OpenSSL independent body");
		assertThat(email.getOriginalSmimeDetails().getVerificationStatus()).isEqualTo(VerificationStatus.VALID);
		assertThat(email.getOriginalSmimeDetails().getOriginalProtectedMessage()).containsExactly(wireMessage);
	}

	@Test
	public void rejectsChangedContentInOpenSslDetachedSignature() throws Exception {
		final byte[] wireMessage = readOpenSslFixture();
		final String original = new String(wireMessage, StandardCharsets.ISO_8859_1);
		final String tampered = original.replace("OpenSSL independent body", "OpenSSL compromised body");
		assertThat(tampered).isNotEqualTo(original);

		final Email email = EmailConverter.emlToEmail(new ByteArrayInputStream(
				tampered.getBytes(StandardCharsets.ISO_8859_1)));

		assertThat(email.getPlainText()).contains("OpenSSL compromised body");
		assertThat(email.getOriginalSmimeDetails().getVerificationStatus()).isEqualTo(VerificationStatus.INVALID);
	}

	private static byte[] readOpenSslFixture() throws Exception {
		return Base64.getMimeDecoder().decode(Files.readAllBytes(OPENSSL_DETACHED_SIGNATURE));
	}
}
