simplejavamail.defaults.bcc.name=BCC Spring
simplejavamail.javaxmail.debug-out=STDERR
simplejavamail.defaults.body.html.content.transfer.encoding=BINARY
simplejavamail.defaults.delivery.status.notification.return.option=HEADERS_ONLY
simplejavamail.smtp.clienthostname=mailer.spring.example.com
simplejavamail.smtp.localaddress=192.0.2.30
simplejavamail.smtp.localport=25259
simplejavamail.dkim.signing.selector=
simplejavamail.extraproperties.two=two
simplejavamail.extraproperties.three=three
