simplejavamail.defaults.bcc.name=BCC Spring
simplejavamail.defaults.body.html.content.transfer.encoding=BINARY
simplejavamail.dkim.signing.selector=
simplejavamail.extraproperties.two=two
simplejavamail.extraproperties.three=three
